#!/usr/bin/env python3
"""Package the finalized Universal source as a deterministic, checked CI patch.

Only Kotlin application/test sources and the four explicit release files enter
the payload. No credentials, local settings, build outputs, binaries, or retired
main-app files are included. Run this after changing the release source.
"""
from __future__ import annotations

import argparse
import base64
import gzip
import hashlib
import json
from pathlib import Path
import textwrap

STATIC_FILES = (
    "app/build.gradle.kts",
    "README.md",
    "USER_GUIDE.md",
    "RELEASE_NOTES_v1.0.15.md",
)

TEMPLATE = r'''#!/usr/bin/env python3
"""Apply the verified Universal v1.0.15 release; never modify the retired app.

Generated by package-universal-release.py from finalized, tested local sources.
The embedded file allowlist and checksums are verified before the first write.
"""
from __future__ import annotations

import argparse
import base64
import gzip
import hashlib
import json
from pathlib import Path, PurePosixPath
import re

ALLOWED_FILES = __ALLOWED_FILES__
PAYLOAD_SHA256 = "__PAYLOAD_SHA256__"
PAYLOAD_B64 = (
__PAYLOAD_B64__
)


def safe_target(root: Path, relative: str) -> Path:
    part = PurePosixPath(relative)
    if (part.is_absolute() or not part.parts or
            any(p in (".", "..") for p in part.parts) or
            "\\" in relative or ":" in relative or str(part) != relative):
        raise ValueError(f"Unsafe release path: {relative!r}")
    target = root.joinpath(*part.parts).resolve()
    if target == root or not target.is_relative_to(root):
        raise ValueError(f"Release path escapes project: {relative!r}")
    return target


def require_universal(text: str) -> None:
    ids = re.findall(r'(?m)^\s*applicationId\s*=\s*"([^"\r\n]+)"', text)
    if ids != ["io.mirr.plexplay.universal"]:
        raise ValueError("Only the Universal application may receive this release")


def apply(root: Path, dry_run: bool = False, check: bool = False) -> int:
    root = root.resolve(strict=True)
    require_universal(safe_target(root, "app/build.gradle.kts").read_text(encoding="utf-8-sig"))
    compressed = base64.b64decode(PAYLOAD_B64, validate=True)
    if hashlib.sha256(compressed).hexdigest() != PAYLOAD_SHA256:
        raise ValueError("Release payload checksum mismatch")
    payload = json.loads(gzip.decompress(compressed).decode("utf-8"))
    if set(payload) != {"schema", "version", "files"} or payload["schema"] != 1 or payload["version"] != "1.0.15":
        raise ValueError("Unexpected Universal release payload")
    files = payload["files"]
    if not isinstance(files, dict) or set(files) != set(ALLOWED_FILES):
        raise ValueError("Release payload does not match its allowlist")
    writes = []
    for relative in ALLOWED_FILES:
        entry = files[relative]
        if not isinstance(entry, dict) or set(entry) != {"text", "sha256"} or not isinstance(entry["text"], str):
            raise ValueError(f"Invalid release entry: {relative}")
        data = entry["text"].encode("utf-8")
        if hashlib.sha256(data).hexdigest() != entry["sha256"]:
            raise ValueError(f"Release file checksum mismatch: {relative}")
        if relative == "app/build.gradle.kts":
            require_universal(entry["text"])
            if (re.findall(r'(?m)^\s*versionCode\s*=\s*(\d+)', entry["text"]) != ["16"] or
                    re.findall(r'(?m)^\s*versionName\s*=\s*"([^"]+)"', entry["text"]) != ["1.0.15"]):
                raise ValueError("Unexpected Universal version")
        target = safe_target(root, relative)
        # Compare decoded text so Windows CRLF is not a false source difference.
        if not target.is_file() or target.read_text(encoding="utf-8-sig") != entry["text"]:
            writes.append((target, data))
    if check and writes:
        raise ValueError(f"Release source differs in {len(writes)} files")
    if not dry_run and not check:
        for target, data in writes:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(data)
    print(f"Universal 1.0.15: {len(files)} source files verified; {len(writes)} "
          f"files {'would change' if dry_run else 'differ' if check else 'updated'}")
    return len(writes)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", type=Path, nargs="?", default=Path.cwd())
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--dry-run", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    apply(args.root, args.dry_run, args.check)
'''


def package(root: Path) -> Path:
    root = root.resolve(strict=True)
    paths = sorted(set(STATIC_FILES) | {
        p.relative_to(root).as_posix()
        for directory in ("app/src/main/java", "app/src/test")
        for p in (root / directory).rglob("*.kt")
    })
    if not any(p.endswith("WatchedCollectionPolicy.kt") for p in paths):
        raise ValueError("Missing watched collection implementation")
    if not any(p.endswith("PlexApiCollectionTest.kt") for p in paths):
        raise ValueError("Missing collection API tests")
    files = {}
    for relative in paths:
        target = (root / relative).resolve(strict=True)
        if not target.is_relative_to(root):
            raise ValueError(f"Source path escapes project: {relative}")
        text = target.read_text(encoding="utf-8-sig")
        files[relative] = {"text": text, "sha256": hashlib.sha256(text.encode("utf-8")).hexdigest()}
    raw = json.dumps({"schema": 1, "version": "1.0.15", "files": files},
                     ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")
    compressed = gzip.compress(raw, compresslevel=9, mtime=0)
    encoded = base64.b64encode(compressed).decode("ascii")
    script = (TEMPLATE.replace("__ALLOWED_FILES__", repr(tuple(paths)))
              .replace("__PAYLOAD_SHA256__", hashlib.sha256(compressed).hexdigest())
              .replace("__PAYLOAD_B64__", "\n".join(f'    "{line}"' for line in textwrap.wrap(encoded, 100))))
    output = root / "scripts/apply-universal-release.py"
    output.write_text(script, encoding="utf-8", newline="\n")
    print(f"Packaged {len(paths)} Universal files; compressed payload {len(compressed)} bytes")
    print(f"Payload SHA-256: {hashlib.sha256(compressed).hexdigest()}")
    return output


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", type=Path, nargs="?", default=Path(__file__).resolve().parent.parent)
    args = parser.parse_args()
    package(args.root)
